# Name: SREENIVASAN S
# Reg: 21BEC0256
# Task -> 3

# Stage 1: Builder
FROM debian:stable-slim AS compiler

# Configure environment
ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Install necessary packages
RUN apt-get update && apt-get install -y \
  python3 python3-pip automake build-essential pkg-config \
  libffi-dev libgmp-dev libssl-dev libtinfo-dev systemd \
  libsystemd-dev libsodium-dev libsodium23 zlib1g-dev \
  npm yarn make g++ tmux git jq wget libncursesw5 gnupg \
  libtool autoconf curl \
  && apt-get clean

# Set up GHC
RUN wget https://downloads.haskell.org/ghc/8.10.7/ghc-8.10.7-x86_64-deb10-linux.tar.xz \
  && tar -xf ghc-8.10.7-x86_64-deb10-linux.tar.xz \
  && cd ghc-* \
  && ./configure && make install \
  && cd .. && rm -rf ghc-*

# Install Cabal
RUN wget https://downloads.haskell.org/~cabal/cabal-install-3.8.1.0/cabal-install-3.8.1.0-x86_64-linux-deb10.tar.xz \
  && tar -xf cabal-install-3.8.1.0-x86_64-linux-deb10.tar.xz \
  && mv cabal /usr/bin/ \
  && rm cabal-install-3.8.1.0-x86_64-linux-deb10.tar.xz \
  && cabal update

# Build and install libsodium
RUN git clone https://github.com/input-output-hk/libsodium \
  && cd libsodium \
  && git checkout dbb48cc \
  && ./autogen.sh && ./configure && make && make install \
  && cd .. && rm -rf libsodium

# Set up library paths
ENV LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" 
ENV PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"

# Build and install secp256k1
RUN git clone https://github.com/bitcoin-core/secp256k1 \
  && cd secp256k1 \
  && git checkout ac83be33 \
  && ./autogen.sh \
  && ./configure --enable-module-schnorrsig --enable-experimental \
  && make && make check && make install \
  && cd .. && rm -rf secp256k1

# Build Cardano Node
RUN git clone https://github.com/input-output-hk/cardano-node.git \
  && cd cardano-node \
  && git checkout 8.2.0-pre \
  && cabal configure --with-compiler=ghc-8.10.7 \
  && echo "package cardano-crypto-praos\n flags: -external-libsodium-vrf" >> cabal.project.local \
  && cabal update && cabal build all

# Install Cardano binaries
RUN mkdir -p $HOME/.local/bin \
  && cp -p "$(./cardano-node/scripts/bin-path.sh cardano-node)" $HOME/.local/bin/ \
  && cp -p "$(./cardano-node/scripts/bin-path.sh cardano-cli)" $HOME/.local/bin/

# Stage 2: Final image
FROM debian:stable-slim

# Copy binaries and libraries from builder
COPY --from=compiler /root/.local/bin/cardano-* /usr/local/bin/
COPY --from=compiler /usr/local/lib/libsodium* /usr/local/lib/
COPY --from=compiler /usr/local/lib/libsecp256k1* /usr/local/lib/

# Install runtime dependencies
RUN apt-get update && apt-get install -y \
  curl dnsutils jq net-tools procps python3 python3-pip \
  telnet tmux vim wget bc \
  && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app